### ISSUE TITLE
Only a Test compile with Mono 5.x

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Merger#8]
Hello ;D
I have **only make a only a test run with mono 5.x** and becomes after the compile run this messages

https://paste.md-5.net/rebehahiti.coffee

**Comment by emperorstarfinder** [comment]
The WhiteCore-Merger repository is meant only for experimentation at this time.  and is not an official WhiteCore-Sim repository currently.

Please use WhiteCore-Dev repository for the official WhiteCore-Sim development code.

This is a known bug.  It is caused due to the fact that not all upgrades are in place yet.
